Repository dwyl/fields, pull requests merged in 2019-11, with the labels that each got.

#47 update ecto version
  mix.exs
  mix.lock
Labels: awaiting-review

#51 PR: Add Coverage Tracking issue #50
  .DS_Store
  .travis.yml
  README.md
  mix.exs
  mix.lock
  test/address_test.exs
  test/email_test.exs
  test/phone_test.exs
  test/postcode_test.exs
Labels: awaiting-review

#55 encrypt decrypt with key_id prepend in value
  lib/address_encrypted.ex
  lib/aes.ex
  lib/email_encrypted.ex
  lib/encrypted.ex
  lib/phone_number_encrypted.ex
  lib/postcode_encrypted.ex
  mix.exs
  test/address_test.exs
  test/aes_test.exs
  test/email_test.exs
  test/encrypted_test.exs
  test/phone_test.exs
  test/postcode_test.exs
Labels: in-review

#58 Add secret_key_base to config issue#57
  .env_sample
  .travis.yml
  config/config.exs
  config/test.exs
  mix.exs
  test/email_test.exs
  test/hash_test.exs
  test/helpers_test.exs
Labels: chore, in-review
